### ISSUE TITLE
vstart, ethX not showing, man

### ISSUE THREAD

**Issue by Pastello** [Kidel/Kathara#10]
Ciao, scusate, non sono sicuro che i commenti postati dopo la chiusura di uno issue vi arrivano, quindi vorrei riportare qui alcuni problemi che ancora mi rimangono:

- [ethX non compare in `ifconfig`](https://github.com/Kidel/Kathara/issues/6)
- [non riesco ad eseguire `vstart`](https://github.com/Kidel/Kathara/issues/9)
- [sarebbe possibile avere anche il comando `man`?](https://github.com/Kidel/Kathara/issues/5)

Grazie

**Comment by Kidel** [comment]
Le notifiche arrivano. E' il tempo che manca :D
