### ISSUE TITLE
docker privileged(ubuntu) bug

### ISSUE THREAD

**Issue by daxingxing88** [Kidel/Kathara#4]
hi, when i start a lab using kathara, it prompts "tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied" and the tcpdump command doesn't work.
I try to search the solution to this question by google and find that this may be docker privileged(ubuntu) bug , and the solution that it works is below:
!!!!!!run the following command in docker, it can solve the problem temporarily.
mv /usr/sbin/tcpdump /usr/bin/tcpdump
ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
I suggest that the above commands can be added to the docker image to solve this issue.

**Comment by Kidel** [comment]
Yes, this was an issue discovered by @glospoto a while ago. 
Thank you for bringing it up!
We will add it to our netkit_base and p4 images as soon as possible.

**Comment by Kidel** [comment]
This issue should be solved now. 
Please run the install script again (`$NETKIT_HOME/install` on Unix and `%NETKIT_HOME%\install` on Windows)
