### ISSUE TITLE
Missing brctl

### ISSUE THREAD

**Issue by Pastello** [Kidel/Kathara#5]
Ciao, non sono riuscito ad eseguire il comando brctl perché non risulta installato il package bridge-utils. Nei lab sul sito di Netkit invece se ne fa uso normalmente senza dover installare nulla

**Comment by Kidel** [comment]
Lo installo contestualmente a #4 
Grazie per la segnalazione

**Comment by Kidel** [comment]
This issue should be solved now. 
Please run the install script again (`$NETKIT_HOME/install` on Unix and `%NETKIT_HOME%\install` on Windows)

**Comment by Pastello** [comment]
Grazie. Per sicurezza vorrei chiederti se basta eseguire lo script `install` oppure se devo prima cancellare qualche altro file o container/immagine

**Comment by Kidel** [comment]
sempre meglio fare lwipe e poi install, ma anche invertendo non dovrebbe cambiare molto.
