### ISSUE TITLE
Cannot chain lwipe with other commands

### ISSUE THREAD

**Issue by Pastello** [Kidel/Kathara#8]
Executing commands like this: `lwipe && <other-command>` does not work

**Comment by Kidel** [comment]
What OS are you using? 
Try `lwipe ; <other-command>` if you're on Unix. 
Or `lwipe & <other-command>` if you're on Windows.  (`&&` requires the first command to return an exit status)

**Comment by Pastello** [comment]
Ok grazie. Speravo di poter mettere due comandi (`lwipe` e `lstart`) in catena così da poter cancellare la memoria precedente e riavviare il lab da zero

**Comment by Kidel** [comment]
Di fatto per quello c'è `lrestart`
Il comando `lwipe` è un po' estremo e serve a cancellare lo stato interno di katharà se si verificano inconsistenze (magari dovute ad interazioni da docker senza passare per katharà). Non dovrebbe essere necessario in condizioni normali.

lrestart di fatto chaina lclean ed lstart.
