### ISSUE TITLE
No such file or directory when using vstart

### ISSUE THREAD

**Issue by Pastello** [Kidel/Kathara#9]
`vstart pc1 --eth 0:A` does not work. I also tried other ways but could not let it work

**Comment by Kidel** [comment]
The syntax is wrong, try `vstart --eth 0:A pc1`
I'll specify it in the readme.

**Comment by Pastello** [comment]
Ancora non funziona. Questo è l'output:
```
Traceback (most recent call last):
  File "/home/pastello/Applicazioni/Kathara/Kathara/bin/python/vstart.py", line 236, in <module>
    start_new_machine()
  File "/home/pastello/Applicazioni/Kathara/Kathara/bin/python/vstart.py", line 190, in start_new_machine
    create_lab(machine_path, args.machine_name, conf_lines)
  File "/home/pastello/Applicazioni/Kathara/Kathara/bin/python/vstart.py", line 176, in create_lab
    os.mkdir(machine_path)
OSError: [Errno 2] No such file or directory: '/home/pastello/netkit_temp/labs/netkit_1000_pc1'
usage: check.py [-h] [-d DIRECTORY] [-f] [-F] path
check.py: error: argument -d/--directory: expected one argument
usage: print_metadata.py [-h] [-d DIRECTORY] [--print] path
print_metadata.py: error: argument -d/--directory: expected one argument
usage: folder_hash.py [-h] [-d DIRECTORY] [--print] path
folder_hash.py: error: argument -d/--directory: expected one argument
Error response from daemon: No such container: netkit_1000_pc1
Error: failed to start containers: netkit_1000_pc1
```

**Comment by Kidel** [comment]
credo ci sia un problema di permessi. Prova a rilanciare install e lwipe e dimmi come va. 
vstart è un'interfaccia rapida per lstart. Quello che dovrebbe fare è creare un lab "temporaneo" e poi ci lancia lstart con parametro -d (dando la directory temporanea). 
Per qualche motivo non viene creata correttamente.

Purtroppo non riesco a riprodurre l'errore.

**Comment by Kidel** [comment]
Mi sembra proprio il caso dello stato interno di Katharà non aggiornato. 
Docker infatti risponde `Error response from daemon: No such container: netkit_1000_pc1`
Vuol dire che invece di `docker run` viene eseguito `docker start` perchè Katharà crede che il container sia in esecuzione. 

Lancia `vclean pc1` e `lwipe`.
Dovrebbe risolvere. 

Altrimenti è un problema di permessi. 
vstart è un'interfaccia rapida per lstart. Quello che dovrebbe fare è creare un lab "temporaneo" e poi lancia lstart con parametro -d (dando la directory temporanea).
`/home/pastello/netkit_temp/labs/netkit_1000_pc1` non è altro che un lab temporaneo creato sulla base dei parametri di vstart (e poi eliminato in automatico dopo che viene lanciato il comando).

**Comment by Kidel** [comment]
Dopo aver lanciato `lwipe` controlla che in `/home/pastello/netkit_temp/` non ci siano file con nomi strani (sono hash relativi a lab che contengono lo stato iniziale dell'esecuzione di lstart).

**Comment by Pastello** [comment]
Ok funziona. Credevo di averlo già fatto prima, quindi o sbagliavo qualcosa o anche questo problema si è corretto reinstallando kathara'.
Grazie

**Comment by NeejaYanglea** [comment]
Più probabile che si sia corretto con lwipe. Concordo con Gaetano, Katharà credeva che la macchina fosse running.
